/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KUBUS;

import Persistance.Buku;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author lmao
 */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/

public class SaranJudulBukuApp extends javax.swing.JFrame {
    
    private JTextField judulBukuTextField;
    private JComboBox<String> saranComboBox;

    private static final EntityManagerFactory emf = Persistence.createEntityManagerFactory("KumpulanBukuSkripsiPU");

    public SaranJudulBukuApp() {
        setTitle("Saran Judul Buku App");
        setSize(400, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

        judulBukuTextField = new JTextField();
        saranComboBox = new JComboBox<>();

        judulBukuTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateSaranComboBox();
            }
        });

        panel.add(new JLabel("Judul Buku:"));
        panel.add(judulBukuTextField);
        panel.add(new JLabel("Saran:"));
        panel.add(saranComboBox);

        add(panel);
    }

    private void updateSaranComboBox() {
        String judulBuku = judulBukuTextField.getText();
        List<Buku> saranJudulBuku = cariSaranJudulBuku(judulBuku);

        saranComboBox.removeAllItems();
        for (Buku saran : saranJudulBuku) {
            saranComboBox.addItem(judulBuku);
        }
    }

    private List<Buku> cariSaranJudulBuku(String judulBuku) {
        EntityManager em = emf.createEntityManager();

        try {
            // Menggunakan named query untuk mencari saran judul buku
            TypedQuery<Buku> query = em.createNamedQuery("Buku.findJudulbuku", Buku.class);
            query.setParameter("SELECT b.judulbuku FROM Buku b WHERE b.judulbuku LIKE LOWER", "%" + judulBuku + "%");

            return query.getResultList();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        } finally {
            em.close();
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new SaranJudulBukuApp().setVisible(true);
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
